config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  
  get 'pages/patient_search' => 'pages#patientSearchPage', as: "search"
  
  get 'pages/doctor' => 'pages#doctorView', as: "doctor"
  get 'pages/medical' => 'pages#medicalView', as: "medical"
  get 'pages/office' => 'pages#officeView', as: "office"
  get 'pages/volunteer' => 'pages#volunteerView', as: "volunteer"
  get 'pages_patient_results' => "pages#pagesPatientResults", as: "pages_patient_results"
  
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  #devise_for :users
  
  devise_for :users, controllers: {
    sessions: 'users/sessions'
  }
  
  #let the pass controller do the necessary route directing
  root :to => 'pass#index'
  resources :pages
  resources :patients
    
  #resources :pages do 
    #get 'pages/patient_search', to: 'pages#patientSearchPage', as: :patient_search
  #end
  
  #If a route isn't recognized then let error controller handle it, this needs to be on the last line
  get '*path' => 'error_routes#routing'
end

app/models/ability.rb
class Ability
  include CanCan::Ability

  def initialize(user)
    user ||= User.new
    
    if user.superadmin_role?
      can :manage, :all
      can :access, :rails_admin
      can :dashboard 
    # elsif user.doctor_role?
    #   cannot :create, Patient
    #   cannot :delete, Patient
      
      #can :manage, :all
      #can :access, :rails_admin       # only allow admin users to access Rails Admin
    end
    
   
    
    # Define abilities for the passed in user here. For example:
    #
    #if user.superadmin_role?
      #can :manage, all
      #can :access, rails_admin
    #end
    
    
       #user ||= User.new # guest user (not logged in)
       #if user.superadmin_role?
         #can :manage, :all
       #end

	
       #user ||= User.new # guest user (not logged in)
       #if user.superadmin_role?
          #can :manage, :all
          #can :access, :rails_admin
       #if user.doctor_role? || user.office_role? || user.volunteer_role? || user.medical_role?
          #can :pages
       #end
    
    
    
    #   else
    #     can :read, :all
    #   end
    #
    # The first argument to `can` is the action you are giving the user
    # permission to do.
    # If you pass :manage it will apply to every action. Other common actions
    # here are :read, :create, :update and :destroy.
    #
    # The second argument is the resource the user can perform the action on.
    # If you pass :all it will apply to every resource. Otherwise pass a Ruby
    # class of the resource.
    #
    # The third argument is an optional hash of conditions to further filter the
    # objects.
    # For example, here the user can only update published articles.
    #
    #   can :update, Article, :published => true
    #
    # See the wiki for details:
    # https://github.com/CanCanCommunity/cancancan/wiki/Defining-Abilities
  end
end

app/models/admittance.rb
class Admittance < ApplicationRecord
    belongs_to :patient
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/bill.rb
class Bill < ApplicationRecord
    belongs_to :discharge
    has_many :charges, dependent: :destroy
    accepts_nested_attributes_for :charges
end

app/models/charge.rb
class Charge < ApplicationRecord
    belongs_to :bill
end

app/models/contact.rb
class Contact < ApplicationRecord
    belongs_to :patient
end

app/models/discharge.rb
class Discharge < ApplicationRecord
    belongs_to :patient
    has_one :bill, dependent: :destroy
    accepts_nested_attributes_for :bill
end

app/models/dr_note.rb
class DrNote < ApplicationRecord
    belongs_to :treatment
end

app/models/emergency_contact.rb
class EmergencyContact < ApplicationRecord
    belongs_to :patient
end

app/models/insurance.rb
class Insurance < ApplicationRecord
    belongs_to :patient
end

app/models/location.rb
class Location < ApplicationRecord
    belongs_to :patient
end

app/models/n_note.rb
class NNote < ApplicationRecord
    belongs_to :treatment
end

app/models/patient.rb
class Patient < ApplicationRecord
    
    has_one :physician, dependent: :destroy
    has_one :emergency_contact, dependent: :destroy
    has_one :contact, dependent: :destroy
    has_one :location, dependent: :destroy
    has_one :admittance, dependent: :destroy
    has_one :discharge, dependent: :destroy
    has_one :insurance, dependent: :destroy
    has_one :treatment, dependent: :destroy
    accepts_nested_attributes_for :physician
    accepts_nested_attributes_for :emergency_contact
    accepts_nested_attributes_for :contact
    accepts_nested_attributes_for :physician
    accepts_nested_attributes_for :location
    accepts_nested_attributes_for :admittance
    accepts_nested_attributes_for :insurance
    accepts_nested_attributes_for :discharge
    accepts_nested_attributes_for :treatment
    
    def self.search(search)
      if search
        where('last_name LIKE ?', "%#{search}%").order('id DESC')
      else
        order('id DESC') 
      end
    end
    
    
end

app/models/physician.rb
class Physician < ApplicationRecord
    belongs_to :patient
end

app/models/prescription.rb
class Prescription < ApplicationRecord
    belongs_to :treatment
end

app/models/schedule.rb
class Schedule < ApplicationRecord
    belongs_to :treatment
end

app/models/treatment.rb
class Treatment < ApplicationRecord
    belongs_to :patient
    has_many :prescriptions, dependent: :destroy
    has_many :schedules, dependent: :destroy
    has_many :dr_notes, dependent: :destroy
    has_many :n_notes, dependent: :destroy
    accepts_nested_attributes_for :schedules
    accepts_nested_attributes_for :prescriptions
    accepts_nested_attributes_for :dr_notes
    accepts_nested_attributes_for :n_notes
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/pass_helper.rb
module PassHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Patient Information Management System</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <nav class="navbar navbar-expand-lg navbar-inverse" style="margin: 0;">
      <div class="container-fluid">
        <div class="navbar-header">
          <%= link_to "Hospital Home", new_user_session_path, class: "navbar-brand"%>
        </div>
	  <div class="collapse navbar-collapse">
        <ul class="nav navbar-nav">
          <li id="date-nav"></li>
        </ul>
        <ul class="nav navbar-nav navbar-right">
          <% if !user_signed_in? || current_user.nil? %>
            <li><%= link_to "Log in", new_user_session_path, class: 'login-button' %></li>
          <% else %>
            <li><%= link_to "Log Out", destroy_user_session_path, class: 'login-button', method: :delete %></li>
          <% end %>
	    </ul>
        </div>
	  </div>
	</nav>
    
    <div class="notice-div">
      <% if notice %>
        <p class="alert alert-success"><%= notice %></p>
      <% end %>
      <% if alert %>
        <p class="alert alert-danger"><%= alert %></p>
      <% end %>
    </div>
    
    <%= yield %>
    
  <script type="text/javascript">
     $(document).ready(function(){
       todayDate();
       $('.alert').fadeIn(1000).delay(5000).fadeOut('fast');
     })
    
      function todayDate(){
        var months = ["January", "February", "March", "April", "May", "June", "July", "August", "September", "October", "November", "December"];
		var days = ["Sunday", "Monday", "Tuesday", "Wednsday", "Thursday", "Friday", "Saturday"];
		var theDate = new Date();
		var year = theDate.getFullYear(), month = months[theDate.getMonth()], date = theDate.getDate();
		var day = days[theDate.getDay()];
		var fullDate = "Today's date is " + day + ", " + month + " " + date + ", " + year;
		document.getElementById("date-nav").innerHTML = fullDate;
      }
  </script>
    
  </body>
</html>

app/views/layouts/pagesPatientResults.html.erb
<html>
    <head>
        <title="Pages/">
        <%= stylesheet_link_tag "https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" %>
        <%= stylesheet_link_tag "pagesPatientResults" %>
        
    </head>
    <body>
      
    <nav class="navbar navbar-expand-lg navbar-inverse" style="margin: 0;">
      <div class="container-fluid">
        <div class="navbar-header">
          <%= link_to "Hospital Home", new_user_session_path, class: "navbar-brand"%>
        </div>
	  <div class="collapse navbar-collapse">
        <ul class="nav navbar-nav">
          <li id="date-nav"></li>
        </ul>
        <ul class="nav navbar-nav navbar-right">
          <% if !user_signed_in? || current_user.nil? %>
            <li><%= link_to "Log in", new_user_session_path, class: 'login-button' %></li>
          <% else %>
            <li><%= link_to "Log Out", destroy_user_session_path, class: 'login-button', method: :delete %></li>
          <% end %>
	    </ul>
        </div>
	  </div>
	</nav>
    
    <div class="notice-div">
      <% if notice %>
        <p class="alert alert-success"><%= notice %></p>
      <% end %>
      <% if alert %>
        <p class="alert alert-danger"><%= alert %></p>
      <% end %>
    </div>
      
      
        <%= yield %>
    </body>
</html>

app/views/pages/_form.html.erb
<%= simple_form_for @patient do |f| %>
<%if current_user.office_role%>
    <%= f.input :first_name, label: "First Name" %>
    <%= f.input :last_name, label: "Last Name" %>
    <%= f.input :middle_name, label: "Middle Name" %>

    <%= f.input :@contact.home_phone, label: "Home Telephone"%>
    <%= f.input :@contact.work_phone, label: "Work Telephone"%>
    <%= f.input :@contact.mobile_phone, label: "Mobile Telephone"%>
    <%= f.input :@contact.street, label: "Street Address"%>
    <%= f.input :@contact.city, label: "City"%>
    <%= f.input :@contact.state, label: "State"%>
    <%= f.input :@contact.zip, label: "ZIP"%>

    <%= f.input :@admittance.reason, label: "Reason for Visit"%>

    <%= f.input :@insurance.policy_num, label: "Insurance Policy Number"%>
    <%= f.input :@insurance.policy_name, label: "Insurance Policy Name"%>
    <%= f.input :@insurance.group_num, label: "Insurance Policy Group Number"%>

    <%= f.input :@location.facility, label: "Facility"%>
    <%= f.input :@location.room, label: "Room"%>
    <%= f.input :@location.bed, label: "Bed"%>
    <%= f.input :@location.visitor_limit, label: "Visitor Limit"%>
    <%= f.input :@location.approved_visitors, label: "Approved Visitors"%>
    <%= f.input :@location.facility, label: "Facility"%>
<%end%>


<%end%>

app/views/pages/doctorView.html.erb
<% require_relative('./HelperDisplayFunctions') 
%>

<h1>Welcome to Doctor Page</h1>

<div class="container">
    <h2>Patient Listing</h2>
    <table class="table table-striped">
<thead>
      <tr>
        <th>Lastname</th>
        <th>Firstname</th>
        <th>Middlename</th>
        <th>Admittance</th>        
        <th>Treatment</th>
        <th>Family Physician</th>
        <th>Faciliity</th>  
        <th>Room</th> 
        <th>Discharge</th>
      </tr>
</thead>
    <tbody> 
        
    
<% @patients.each do |patient| %>
<tr> 

        <td><%= HelperDisplay.nametry(patient.last_name) %></td>
        <td><%= HelperDisplay.nametry(patient.first_name) %></td>
        <td><%= HelperDisplay.nametry(patient.middle_name) %></td>
        <td><%= HelperDisplay.datetry(patient.admittance) %></td>
        <td><%= HelperDisplay.treatmenttry(patient.treatment) %></td>
        <td><%= HelperDisplay.fphysiciantry(patient.physician) %></td>
        <td><%= HelperDisplay.facilitytry(patient.location) %></td>
        <td><%= HelperDisplay.roomtry(patient.location) %></td>
        <td><%= HelperDisplay.datetry(patient.discharge) %></td>
        <td><%= link_to "View", page_path(patient) %></td>
</tr>        
<%end%>        
    
    </tbody>
  </table>

</div>

app/views/pages/index.html.erb
<h2>If I'm seen then we have error</h2>

app/views/pages/medicalView.html.erb
<h1>Welcome to Medical Page</h1>

<div class="container">
    <h2>Patient Listing</h2>
    <table class="table table-striped">
<thead>
      <tr>
        <th>Lastname</th>
        <th>Firstname</th>
        <th>Middlename</th>
        <th>Admittance</th>        
        <th>Treatment</th>
        <th>Family Physician</th>
        <th>Faciliity</th>  
        <th>Room</th> 
        <th>Discharge</th>
      </tr>
    </thead>
    <tbody>
<% @patients.each do |patient|%>
    <tr>
        <td><%= patient.last_name %></td>
        <td><%= patient.first_name %></td>
        <td><%= patient.middle_name %></td>
        <td><%= @admittance.date %></td>
        <td><%= @treatment.name %></td>
        <td><%= @physician.family_physician%></td>
        <td><%= @location.facility %></td>
        <td><%= @location.room %></td>
        <td><%= @discharge.date %></td>
    </tr>
<%end%>    
    </tbody>
  </table>
</div>

app/views/pages/new.html.erb
<h1>New Patient</h1>
<%= render %>

app/views/pages/officeView.html.erb
<h1>Welcome to Office Page</h1>
<div class="container">
    <h2>Patient Listing</h2>
    <table class="table table-striped">
<thead>
      <tr>
        <th>Lastname</th>
        <th>Firstname</th>
        <th>Middlename</th>
        <th>Admittance</th>
        <th>Faciliity</th>  
        <th>Room</th> 
        <th>Discharge</th>
      </tr>
    </thead>
    <tbody>
<% @patients.each do |patient|%>
    <tr>
        <td><%= patient.last_name %></td>
        <td><%= patient.first_name %></td>
        <td><%= patient.middle_name %></td>
        <td><%= @admittance.date %></td>
        <td><%= @location.facility %></td>
        <td><%= @location.room %></td>
        <td><%= @discharge.date %></td>
    </tr>
<%end%>     
    </tbody>
  </table>
</div>

app/views/pages/pagesPatientResults.html.erb
<% require_relative('./HelperDisplayFunctions') %>
<%#= provide :stylesheets do %>
  <%#= stylesheet_link_tag "results" %>
<%# end %>

<h2 class="text-center">Patients that matched your search criteria</h2>

<% @patients.first(10).each do |patient| %>
  <div class="patient-card">
    <h3><%= patient.first_name + ", " + patient.last_name %></h3>
    <div>
      <p>Basic Info</p>
      <div class="patient-info-div">
        <p>facility: <%= HelperDisplay.facilitytry(patient.location) %></p>
        <p>room: <%= HelperDisplay.roomtry(patient.location) %></p>
        <p>bed: <%= HelperDisplay.roomtry(patient.location) %></p> <br>
      </div>
      <p>View Complete Profile</p>
      <p class="view-more"><%= link_to "View More", page_path(patient) %></p>
    </div>
  </div>
<% end %>



app/views/pages/patientSearchPage.html.erb
   <% accessVar = "" %>
   <% imagePath = '' %>
   <% if current_user.doctor_role %>
     <% accessVar = "doctor" %>
     <% imagePath = 'doctorStaff.jpg' %>
   <% end %>
   <% if current_user.medical_role %>
     <% accessVar = "medical" %>
     <% imagePath = 'medicalStaff.jpg' %>
   <% end %>
   <% if current_user.office_role %>
     <% accessVar = "office" %>
     <% imagePath = 'officeStaff.jpg' %>
   <% end %>
   <% if current_user.volunteer_role %>
     <% accessVar = "volunteer" %>
     <% imagePath = 'volunteerStaff.jpg' %>
   <% end %>

	<div class="container" id="wrapper">
		<div class="info_boxes" id="info_box1">
			<h1>Patient Search Screen</h1>
			<div class="welcome_box">
				<p> <%= current_user.email %> </p>
				<p>Access Rights: <span id="access_rights"> <%= accessVar %> </span></p>
			</div>
		</div>
		
		<div class="info_boxes" id="info_box2">
			<div class="patient_box">
                <!--
				<form>
					<div class="form-group">
						<label for="First Name">First Name</label>
						<input type="text" name="last name" class="form-control" id="firstName" />
					</div>
					<div class="form-group">
						<label for="First Name">Last Name</label>
						<input type="text" name="last name" class="form-control" id="lastName" />
					</div>
				</form>
                -->
                <div class="form-group">
                  <%#= form_tag(pages_path, method: :get) do %> 
                    <%#= text_field_tag :term, params[:term] %>
                    <%#= submit_tag 'Search' %>
                  <%# end %>
                  
                  <%= form_tag pages_patient_results_path, :method => 'get' do %>
                    <p>
                      <%= text_field_tag :search %>
                      <%= submit_tag "search" %>
                    </p>
                  <% end %>

                </div>


			</div>
			<div class="image_box">
                <%= image_tag(imagePath) %>
			</div>
		</div>

		<div class="info_boxes" id="info_box3">			
			<div class="form-group search_button_div">
                <% if !current_user.superadmin_role? %>
                  <p> Search All Patients</p><br>
                  <%= link_to "Find Patients", {controller: "pages", action: "index"}, class: "btn btn-small btn-success" %>
                <% end %>
                
                <% if accessVar == "office"%>
                  <div class="office_worker_message">
                    <p>If you need to add a new patient instead, click the link below</p>
                    <div class="form-group">
                        <!-- delete the immediate line below once decided on what approach to take -->
                        <a class="" href="#">Go to Add Patient Page</a>
                    </div>
                  </div>
                <% end %>
              
			</div>
            
		</div>
	</div>

app/views/pages/show.html.erb
<% require_relative('./HelperDisplayFunctions') 
%>

<div class="container">
<div id = "patient_wrapper">
<div class = "boxes admit">

<div class = "boxes patient">
<h2>General</h2>
<p class = "first_name"> First Name: <%= HelperDisplay.firsttry(@patient) %> </p>
<p class = "last_name"> Last Name: <%= HelperDisplay.lasttry(@patient) %> </p>
<p class = "middle_name"> Middle Name: <%= HelperDisplay.middletry(@patient) %> </p>
<% if current_user.office_role || current_user.doctor_role || current_user.medical_role %>
<p class = "birthday"> Birthdate: <%= HelperDisplay.birthdaytry(@patient) %> </p>
<%end%>
</div>

<% if current_user.office_role || current_user.doctor_role || current_user.medical_role %>
<h2>Admittance</h2>
<p class = "date_para"> Admittance Date: <%= HelperDisplay.datetry(@patient.admittance)%> </p>
<p class = "time_para"> Admittance Time: <%= HelperDisplay.timetry(@patient.admittance)%> </p>
<p class = "reason_para"> Admittance Reason: <%= HelperDisplay.reasontry(@patient.admittance) %> </p>
<h2>Discharge</h2>
<p class = "date_dis_para"> Discharge Date: <%= HelperDisplay.datetry(@patient.discharge) %> </p>
<p class = "time_dis_para"> Discharge Time: <%= HelperDisplay.timetry(@patient.discharge) %> </p>
</div>
<%end%>

<% if current_user.office_role || current_user.doctor_role || current_user.medical_role %>
<div class = "boxes contact">
<h2>Contact Information</h2>
<p class = "home"> Home Number: <%= HelperDisplay.hometry(@patient.contact) %> </p>
<p class = "work"> Work Number: <%= HelperDisplay.worktry(@patient.contact) %> </p>
<p class = "mobile"> Mobile Number: <%= HelperDisplay.mobiletry(@patient.contact) %> </p>
<p class = "street"> Street Address: <%= HelperDisplay.streettry(@patient.contact)%> </p>
<p class = "city"> City: <%= HelperDisplay.citytry(@patient.contact) %> </p>
<p class = "state"> State: <%= HelperDisplay.statetry(@patient.contact) %> </p>
<p class = "zip"> ZIP: <%= HelperDisplay.ziptry(@patient.contact) %> </p>
</div>
<%end%>

<% if current_user.office_role || current_user.doctor_role || current_user.medical_role %>
<div class = "boxes phy">
<h2>Physician</h2>
<p class = "physician"> Primary Care Physician: <%= HelperDisplay.fphysiciantry(@patient.physician) %> </p>
<p class = "physician_num"> Primary Care Number: <%= HelperDisplay.fp_phonetry(@patient.physician) %> </p>
</div>
<%end%>

<div class = "boxes location">
<h2>Location</h2>
<p class = "facility_para"> Facility: <%= HelperDisplay.facilitytry(@patient.location) %> </p>
<p class = "room_para"> Room: <%= HelperDisplay.roomtry(@patient.location) %> </p>
<p class = "bed_para"> Bed: <%= HelperDisplay.bedtry(@patient.location) %> </p>
<h5><b>Vistor Information</b></h5>
<p class = "vlimit_para"> Visitor Limit: <%= HelperDisplay.vlimittry(@patient.location) %> </p>
<p class = "vapprove_para"> Approved Visitors: <%= HelperDisplay.vapprovedtry(@patient.location) %> </p>
</div>

<% if current_user.doctor_role || current_user.medical_role %>
<div class = "boxes treatment">
<h2>Treatment</h2>
<p class = "treat_para"> Treatment: <%= HelperDisplay.treatmenttry(@patient.treatment) %> </p>
<p class = "med_para"> medication </p>
<p class = "sched_para"> schedule </p>
<p class = "sched_para"> notes </p>
</div>
<%end%>

<% if current_user.office_role %>
<div class = "boxes insurance">
<h2>Insurance</h2>
<p class = "policynum_para"> Policy Number: <%= HelperDisplay.p_numtry(@patient.insurance) %> </p>
<p class = "policy_para"> Policy Name: <%= HelperDisplay.p_nametry(@patient.insurance) %>  </p>
<p class = "group_para"> Group Number: <%= HelperDisplay.grouptry(@patient.insurance) %>  </p>
</div>
<%end%>

<% if current_user.office_role || current_user.doctor_role || current_user.medical_role %>
<div class = "boxes emergency">
<h2>Emergency Contacts</h2>
<h5><b>Contact 1</b></h5>
<p class = "e1_para"> Name: <%= HelperDisplay.e1_try(@patient.emergency_contact) %> </p>
<p class = "e1num_para"> Number: <%= HelperDisplay.e1p_try(@patient.emergency_contact) %>  </p>
<h5><b>Contact 2</b></h5>
<p class = "e2_para"> Name: <%= HelperDisplay.e2_try(@patient.emergency_contact) %>  </p>
<p class = "e2num_para"> Number: <%= HelperDisplay.e2p_try(@patient.emergency_contact) %>  </p>
</div>
<%end%>

</div>
</div>
</div>

app/views/pages/volunteerView.html.erb
<h1>Welcome to Volunteer Page</h1>
<div class="container">
    <h2>Patient Listing</h2>
    <table class="table table-striped">
<thead>
      <tr>
        <th>Lastname</th>
        <th>Firstname</th>
        <th>Middlename</th>
        <th>Faciliity</th>  
        <th>Room</th> 
      </tr>
    </thead>
    <tbody>
<% @patients.each do |patient|%>
    <tr>
        <td><%= patient.last_name %></td>
        <td><%= patient.first_name %></td>
        <td><%= patient.middle_name %></td>
        <td><%= patient.location.facility %></td>
        <td><%= patient.location.room %></td>
    </tr>
<%end%>     
    </tbody>
  </table>
</div>